### ISSUE TITLE
Problem with tensorflow 1.2 and Keras 2.0.2 

### ISSUE THREAD

**Issue by SanjithKanagavel** [keonkim/keras-text-classification#1]
With Tensorflow 1.2 not running properly.

```
Error : ValueError: Shapes must be equal rank, but are 3 and 4 for 'Assign_1' (op: 'Assign') with input shapes: [3,20,128], [3,1,20,128].
```

Edit : Working perfectly with Kekras : 1.2.2  and Tensorflow : 0.9

**Comment by Salakar** [comment]
Same here, stack:

```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(trainable=True, name="embedding_1", activity_regularizer=None, input_dtype="int32", mask_zero=False, input_dim=29689, batch_input_shape=[None, 45], output_dim=20, input_length=45, embeddings_initializer="uniform", embeddings_regularizer=None, embeddings_constraint=None)`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(batch_input_shape=[None, 45,..., trainable=True, name="dropout_1", input_dtype="float32", rate=0.25)`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `InputLayer` call to the Keras 2 API: `InputLayer(batch_input_shape=[None, 45,..., sparse=False, name="input_1", dtype="float32")`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="convolution1d_1", activity_regularizer=None, trainable=True, activation="relu", input_shape=(None, Non..., filters=128, kernel_size=3, strides=1, padding="valid", kernel_initializer="glorot_uniform", kernel_regularizer=None, bias_regularizer=None, kernel_constraint=None, bias_constraint=None, use_bias=True)`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="convolution1d_2", activity_regularizer=None, trainable=True, activation="relu", input_shape=(None, Non..., filters=128, kernel_size=4, strides=1, padding="valid", kernel_initializer="glorot_uniform", kernel_regularizer=None, bias_regularizer=None, kernel_constraint=None, bias_constraint=None, use_bias=True)`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(trainable=True, name="maxpooling1d_1", pool_size=2, strides=2, padding="valid")`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(trainable=True, name="maxpooling1d_2", pool_size=2, strides=2, padding="valid")`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_1", activity_regularizer=None, trainable=True, input_dim=None, activation="linear", units=128, kernel_initializer="glorot_uniform", kernel_regularizer=None, bias_regularizer=None, kernel_constraint=None, bias_constraint=None, use_bias=True)`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(trainable=True, name="dropout_2", rate=0.5)`
  return cls(**config)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py:1242: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_2", activity_regularizer=None, trainable=True, input_dim=None, activation="linear", units=1, kernel_initializer="glorot_uniform", kernel_regularizer=None, bias_regularizer=None, kernel_constraint=None, bias_constraint=None, use_bias=True)`
  return cls(**config)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 670, in _call_cpp_shape_fn_impl
    status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 3 and 4 for 'Assign_1' (op: 'Assign') with input shapes: [3,20,128], [3,1,20,128].
```

**Comment by milyasyousuf** [comment]
@SanjithKanagavel  bro according to read me file this code is based on Theano as backend and using keras over tensorflow.
